apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: default
  labels:
    app: kubevirt-manager
    kubevirt-manager.io/version: 1.3.1
    kubevirt-manager.io/managed: "true"
data:
  .htpasswd: YWRtaW46JGFwcjEkSGhmLkJjUVoka2huQnVKVklDL2VUV25xaVJxLnVULwo=
